const PROJECT={name:'مشروع برج الأعمال',lat:24.4709,lng:39.6122,radius:250};
let selectedRole='worker',workerMap,adminMap,workerMarker,accuracyCircle,hasSelfie=false,isCheckedIn=false,checkInAt=null,currentPosition=null;
const workers=[
{name:'أحمد علي',id:'1021',job:'نجار',time:'06:56 ص',status:'inside',updated:'منذ دقيقة'},
{name:'محمد صالح',id:'1034',job:'حداد',time:'07:01 ص',status:'inside',updated:'منذ دقيقتين'},
{name:'عبدالله حسن',id:'1057',job:'كهربائي',time:'07:04 ص',status:'outside',updated:'منذ 4 دقائق'},
{name:'عمر محمود',id:'1072',job:'سباك',time:'06:59 ص',status:'inside',updated:'منذ 5 دقائق'},
{name:'مصطفى إبراهيم',id:'1088',job:'عامل',time:'--',status:'absent',updated:'لا يوجد'},
{name:'خالد يوسف',id:'1095',job:'مشغل معدات',time:'07:08 ص',status:'outside',updated:'منذ 7 دقائق'},
{name:'سعيد محمد',id:'1113',job:'عامل',time:'07:03 ص',status:'inside',updated:'منذ 8 دقائق'},
{name:'حسن أحمد',id:'1126',job:'مراقب',time:'07:00 ص',status:'inside',updated:'منذ 9 دقائق'}
];
const alerts=[
{name:'عبدالله حسن',text:'خرج من نطاق مشروع برج الأعمال',time:'قبل 4 دقائق',distance:'310 م'},
{name:'خالد يوسف',text:'ما زال خارج النطاق بعد فترة السماح',time:'قبل 7 دقائق',distance:'465 م'},
{name:'ياسر علي',text:'عاد إلى النطاق بعد خروج لمدة 8 دقائق',time:'قبل 18 دقيقة',distance:'داخل الموقع'}
];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function toast(msg,type=''){const el=$('#toast');el.textContent=msg;el.className=`toast show ${type}`;setTimeout(()=>el.className='toast',3000)}
function clock(){const d=new Date();$('#clockText').textContent=d.toLocaleDateString('ar-SA',{weekday:'long',day:'numeric',month:'long'})+' — '+d.toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit',second:'2-digit'});if(isCheckedIn&&checkInAt){const mins=Math.floor((Date.now()-checkInAt)/60000);$('#workedHours').textContent=String(Math.floor(mins/60)).padStart(2,'0')+':'+String(mins%60).padStart(2,'0')}}
setInterval(clock,1000);clock();
$$('.role-btn').forEach(b=>b.onclick=()=>{$$('.role-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedRole=b.dataset.role});
$('#loginForm').onsubmit=e=>{e.preventDefault();if($('#employeeId').value!=='1001'||$('#password').value!=='123456')return toast('بيانات الدخول غير صحيحة','error');openApp(selectedRole)};
function openApp(role){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');const admin=role==='admin';$('#workerDashboard').classList.toggle('hidden',admin);$('#adminDashboard').classList.toggle('hidden',!admin);$('#pageTitle').textContent=admin?'لوحة تحكم الإدارة':'لوحة العامل';$('#pageSubtitle').textContent=admin?'متابعة الحضور ومواقع العمال لحظيًا':'مشروع برج الأعمال — المدينة المنورة';$('#userName').textContent=admin?'مدير النظام':'محمد أحمد';$('#userRole').textContent=admin?'إدارة':'عامل';$('#sideNav').innerHTML=admin?'<button class="nav-item active">لوحة التحكم</button><button class="nav-item">العمال</button><button class="nav-item">المشاريع</button><button class="nav-item">التقارير</button>':'<button class="nav-item active">الرئيسية</button><button class="nav-item">سجل الحضور</button><button class="nav-item">الاستئذانات</button>';setTimeout(()=>admin?initAdmin():initWorker(),100)}
$('#logoutBtn').onclick=()=>location.reload();
function initWorker(){if(workerMap)return;workerMap=L.map('workerMap').setView([PROJECT.lat,PROJECT.lng],16);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(workerMap);L.circle([PROJECT.lat,PROJECT.lng],{radius:PROJECT.radius,color:'#188c61',fillColor:'#49ba8a',fillOpacity:.12,weight:2}).addTo(workerMap).bindPopup(PROJECT.name+' — النطاق المسموح');L.marker([PROJECT.lat,PROJECT.lng]).addTo(workerMap).bindPopup(PROJECT.name);restoreAttendance();locateUser()}
function locateUser(){if(!navigator.geolocation)return toast('المتصفح لا يدعم تحديد الموقع','error');$('#locateBtn').disabled=true;$('#locateBtn').textContent='جاري التحديد...';navigator.geolocation.getCurrentPosition(onLocation,err=>{toast(locationError(err),'error');$('#zoneStatus').textContent='تعذر التحديد';$('#locateBtn').disabled=false;$('#locateBtn').textContent='تحديث الموقع';}, {enableHighAccuracy:true,timeout:12000,maximumAge:0})}
function locationError(err){return err.code===1?'اسمح للموقع من إعدادات المتصفح':err.code===2?'تعذر الحصول على إشارة GPS':'انتهت مهلة تحديد الموقع'}
function onLocation(pos){currentPosition=pos.coords;const {latitude,longitude,accuracy}=pos.coords;const dist=Math.round(distance(latitude,longitude,PROJECT.lat,PROJECT.lng));const inside=dist<=PROJECT.radius;$('#zoneStatus').textContent=inside?'داخل الموقع':'خارج النطاق';$('#zoneStatus').style.color=inside?'var(--success)':'var(--danger)';$('#distanceText').textContent=`تبعد ${dist} مترًا عن مركز الموقع`;$('#accuracyText').textContent=Math.round(accuracy)+' م';$('#attendanceBtn').disabled=!hasSelfie||!inside;$('#locateBtn').disabled=false;$('#locateBtn').textContent='تحديث الموقع';if(workerMarker)workerMap.removeLayer(workerMarker);if(accuracyCircle)workerMap.removeLayer(accuracyCircle);workerMarker=L.marker([latitude,longitude]).addTo(workerMap).bindPopup('موقعك الحالي').openPopup();accuracyCircle=L.circle([latitude,longitude],{radius:accuracy,color:'#20a4b8',fillOpacity:.08,weight:1}).addTo(workerMap);workerMap.fitBounds(L.featureGroup([workerMarker,L.marker([PROJECT.lat,PROJECT.lng])]).getBounds().pad(.35));if(!inside)toast('تنبيه: أنت خارج نطاق المشروع','error');else toast('تم التحقق: أنت داخل نطاق المشروع','success')}
function distance(a,b,c,d){const R=6371000,p=x=>x*Math.PI/180,da=p(c-a),db=p(d-b),v=Math.sin(da/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(db/2)**2;return R*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))}
$('#locateBtn').onclick=locateUser;
$('#selfieBtn').onclick=()=>$('#cameraInput').click();
$('#cameraInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const url=URL.createObjectURL(file);$('#selfiePreview').innerHTML=`<img src="${url}" alt="صورة التحقق">`;hasSelfie=true;$('#selfieBtn').textContent='إعادة التقاط السيلفي';if(currentPosition){const dist=distance(currentPosition.latitude,currentPosition.longitude,PROJECT.lat,PROJECT.lng);$('#attendanceBtn').disabled=dist>PROJECT.radius}toast('تم التقاط السيلفي','success')};
$('#attendanceBtn').onclick=()=>{if(!hasSelfie||!currentPosition)return;if(!isCheckedIn){isCheckedIn=true;checkInAt=Date.now();localStorage.setItem('wt_attendance',JSON.stringify({isCheckedIn,checkInAt}));$('#attendanceBtn').textContent='تسجيل الانصراف';$('#liveBadge').textContent='داخل الدوام';$('#liveBadge').className='status-badge success';$('#checkInTime').textContent=new Date(checkInAt).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'});addTimeline('تم تسجيل الحضور',new Date());toast('تم تسجيل الحضور بنجاح','success')}else{isCheckedIn=false;addTimeline('تم تسجيل الانصراف',new Date());localStorage.removeItem('wt_attendance');$('#attendanceBtn').textContent='تسجيل الحضور';$('#liveBadge').textContent='انتهى الدوام';$('#liveBadge').className='status-badge neutral';toast('تم تسجيل الانصراف بنجاح','success')}};
function addTimeline(text,date){const old=$('#todayTimeline').querySelector('.empty-state');if(old)old.remove();const row=document.createElement('div');row.className='timeline-item';row.innerHTML=`<span class="timeline-dot"></span><strong>${text}</strong><small>${date.toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}</small>`;$('#todayTimeline').prepend(row)}
function restoreAttendance(){try{const x=JSON.parse(localStorage.getItem('wt_attendance'));if(x?.isCheckedIn){isCheckedIn=true;checkInAt=x.checkInAt;$('#attendanceBtn').textContent='تسجيل الانصراف';$('#liveBadge').textContent='داخل الدوام';$('#liveBadge').className='status-badge success';$('#checkInTime').textContent=new Date(checkInAt).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'});addTimeline('الحضور مسجل مسبقًا',new Date(checkInAt))}}catch{}}
function initAdmin(){renderWorkers();renderAlerts();if(adminMap)return;adminMap=L.map('adminMap').setView([PROJECT.lat,PROJECT.lng],16);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(adminMap);L.circle([PROJECT.lat,PROJECT.lng],{radius:PROJECT.radius,color:'#188c61',fillColor:'#49ba8a',fillOpacity:.12,weight:2}).addTo(adminMap);const points=[[24.4712,39.6117,'أحمد علي','inside'],[24.4705,39.6126,'محمد صالح','inside'],[24.4720,39.6128,'عمر محمود','inside'],[24.4699,39.6114,'سعيد محمد','inside'],[24.4742,39.6152,'عبدالله حسن','outside'],[24.4677,39.6085,'خالد يوسف','outside']];points.forEach(([lat,lng,name,status])=>L.circleMarker([lat,lng],{radius:8,color:status==='inside'?'#188c61':'#d94f4f',fillColor:status==='inside'?'#188c61':'#d94f4f',fillOpacity:.9}).addTo(adminMap).bindPopup(`<strong>${name}</strong><br>${status==='inside'?'داخل الموقع':'خارج النطاق'}`))}
function renderWorkers(){const q=($('#workerSearch')?.value||'').trim(),f=$('#statusFilter')?.value||'all';$('#workersTable').innerHTML=workers.filter(w=>(!q||w.name.includes(q)||w.id.includes(q))&&(f==='all'||w.status===f)).map(w=>`<tr><td><div class="worker-name"><span class="mini-avatar">${w.name[0]}</span><strong>${w.name}</strong></div></td><td>${w.id}</td><td>${w.job}</td><td>${w.time}</td><td><span class="pill ${w.status}">${w.status==='inside'?'داخل الموقع':w.status==='outside'?'خارج النطاق':'غائب'}</span></td><td>${w.updated}</td></tr>`).join('')}
function renderAlerts(){if(!$('#alertList'))return;$('#alertList').innerHTML=alerts.map(a=>`<div class="alert-card"><strong>⚠️ ${a.name}</strong><p>${a.text}</p><small>${a.time} — ${a.distance}</small></div>`).join('')}
$('#workerSearch').oninput=renderWorkers;$('#statusFilter').onchange=renderWorkers;$('#simulateAlert').onclick=()=>{const names=['مازن عمر','إبراهيم علي','حسين صالح'];alerts.unshift({name:names[Math.floor(Math.random()*names.length)],text:'خرج للتو من نطاق مشروع برج الأعمال',time:'الآن',distance:(280+Math.floor(Math.random()*180))+' م'});renderAlerts();toast('وصل تنبيه خروج جديد','error')};
